### PR TITLE
#159 Make it possible to customize calculating of record length

### PR DESCRIPTION
**Pull request by rnetuka**
A PR for https://github.com/beanio/beanio/issues/159

There was a request for counting Asian characters as 2 bytes in _fixed length format_. I've added two new options:
- countMode chars|bytes - chars (default) works as now. Bytes count all lengths, paddings, validations etc. by byte count
- charset - charset for determining the byte count for each character

Tested with Japanese and Shift-JIS, it counts all non-ASCII characters as 2 bytes.

Note: the default charset is UTF-8, but I doubt anyone will actually use it. Because of how Unicode works, Japanese strings returns different byte lengths for similar-looking strings. But there has to be some default...

It's still a draft. I have yet to test it more and add unit tests. 

Any comments are welcome!

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks good, then this is possible to configure in a beanio standard way.

**Comment by rnetuka** [comment]
I've added a support for _minLength_ and _maxLength_ validation (missing in the original commit). Also, there's a unit test, but I had to mark it @Ignore as I didn't find a way how to override Settings and than revert to defaults...

**Review by davsclaus — APPROVED** [review]

**Comment by bjansen** [comment]
Yep, I'll review it asap. In the meantime, have you had a chance to test the change on a 'real' project to see if answers your original request?

**Comment by davsclaus** [comment]
Yes we have real projects from our Japanese customers at Red Hat. However we cannot share these in the public.

**Comment by bjansen** [comment]
> I've added a support for _minLength_ and _maxLength_ validation (missing in the original commit). Also, there's a unit test, but I had to mark it @ignore as I didn't find a way how to override Settings and than revert to defaults...

I guess you could use reflection to clear `org.beanio.internal.util.Settings#settings` and to reload new configuration (clear the field in both the setup and teardown methods).

Other than that, this PR looks good to me.

**Comment by bjansen** [comment]
It works with reflection, I'll push a new commit. Thanks a lot for your contribution!

**Comment by davsclaus** [comment]
Thank you very much for the help and the release @bjansen 

BeanIO is a really great library - and we have Camel users that have build integrations and data mapping with 100+ beanio files that does important work.

The last users I heard from were using 150 beanio mappings and was concerned if they would need to migrate to another library - so great to see beanio v3 active and released again.

**Comment by davsclaus** [comment]
And @rnetuka has also helped Jackson to have better support for Japanse characters in the new 2.18.x jackson release - so all together great and important work.

**Pull request merged**
